// <auto-generated />
using System;
using AllegroService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AllegroService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227105615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AllegroService.Domain.Entities.Charge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FolioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolioId");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "FolioId");

                    b.ToTable("Charges", null, t =>
                        {
                            t.HasCheckConstraint("CK_Charges_QtyPositive", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_Charges_TotalNonNegative", "\"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.ChargeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChargeId");

                    b.HasIndex("GlampingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("GlampingId", "ChargeId");

                    b.HasIndex("GlampingId", "ProductId");

                    b.ToTable("ChargeItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChargeItems_QtyPositive", "\"Qty\" > 0");

                            t.HasCheckConstraint("CK_ChargeItems_TotalNonNegative", "\"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Folio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StayId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("StayId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("Folios", (string)null);
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Glamping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Glampings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a11e29d-dfba-4e64-8956-35a3d70ac15f"),
                            Address = "Ruta Escenica 123",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "COP",
                            Name = "Demo Glamping",
                            Timezone = "America/Bogota",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "Email");

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("UnitId");

                    b.HasIndex("GlampingId", "Name")
                        .IsUnique();

                    b.HasIndex("GlampingId", "UnitId");

                    b.ToTable("Locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d9fbbd6-43b7-41fc-9708-c165e27e89df"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47"),
                            GlampingId = new Guid("8a11e29d-dfba-4e64-8956-35a3d70ac15f"),
                            Name = "Main Warehouse",
                            Type = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47")
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolioId");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "FolioId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_AmountPositive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TrackStock")
                        .HasColumnType("boolean");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "CategoryId");

                    b.HasIndex("GlampingId", "Sku")
                        .IsUnique();

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_SalePriceNonNegative", "\"SalePrice\" >= 0");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "Name")
                        .IsUnique();

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a15703c5-f0ab-4d84-9f6d-0549e750dd57"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47"),
                            GlampingId = new Guid("8a11e29d-dfba-4e64-8956-35a3d70ac15f"),
                            Name = "Alimentos",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47")
                        },
                        new
                        {
                            Id = new Guid("95fcb0ac-4d68-44a7-86aa-58f1e129851f"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47"),
                            GlampingId = new Guid("8a11e29d-dfba-4e64-8956-35a3d70ac15f"),
                            Name = "Bebidas",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47")
                        },
                        new
                        {
                            Id = new Guid("3dc17971-ec2a-48d2-b6b6-d52cf52393aa"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47"),
                            GlampingId = new Guid("8a11e29d-dfba-4e64-8956-35a3d70ac15f"),
                            Name = "Extras",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedByUserId = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47")
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CheckInDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOutDate")
                        .HasColumnType("date");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalEstimated")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GuestId");

                    b.HasIndex("UnitId");

                    b.HasIndex("GlampingId", "Code")
                        .IsUnique();

                    b.HasIndex("GlampingId", "GuestId");

                    b.HasIndex("GlampingId", "UnitId");

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Reservations_CheckOutAfterCheckIn", "\"CheckOutDate\" > \"CheckInDate\"");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Stay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CheckOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UnitId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.HasIndex("GlampingId", "UnitId");

                    b.ToTable("Stays", null, t =>
                        {
                            t.HasCheckConstraint("CK_Stays_CheckOutAfterCheckIn", "\"CheckOutAt\" IS NULL OR \"CheckOutAt\" > \"CheckInAt\"");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.StockBalance", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyOnHand")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "LocationId");

                    b.HasIndex("GlampingId");

                    b.HasIndex("LocationId");

                    b.HasIndex("GlampingId", "LocationId");

                    b.HasIndex("GlampingId", "ProductId");

                    b.ToTable("StockBalances", (string)null);
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("GlampingId", "LocationId");

                    b.HasIndex("GlampingId", "ProductId");

                    b.HasIndex("ReferenceType", "ReferenceId");

                    b.ToTable("StockMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockMovements_QtyPositive", "\"Qty\" > 0");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "Name")
                        .IsUnique();

                    b.ToTable("Units", null, t =>
                        {
                            t.HasCheckConstraint("CK_Units_Capacity", "\"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("GlampingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GlampingId");

                    b.HasIndex("GlampingId", "Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c7093d5-0365-4f9c-8bfd-9a6c777b9a47"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@demo-glamping.local",
                            GlampingId = new Guid("8a11e29d-dfba-4e64-8956-35a3d70ac15f"),
                            Name = "Admin",
                            PasswordHash = "CHANGE_ME",
                            Status = 1,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Charge", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Folio", "Folio")
                        .WithMany("Charges")
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Charges")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folio");

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.ChargeItem", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Charge", "Charge")
                        .WithMany("Items")
                        .HasForeignKey("ChargeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("ChargeItems")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Product", "Product")
                        .WithMany("ChargeItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Charge");

                    b.Navigation("Glamping");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Folio", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Folios")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Stay", "Stay")
                        .WithMany("Folios")
                        .HasForeignKey("StayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");

                    b.Navigation("Stay");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Guest", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Guests")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Location", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Locations")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Unit", "Unit")
                        .WithMany("Locations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Glamping");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Payment", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Folio", "Folio")
                        .WithMany("Payments")
                        .HasForeignKey("FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Payments")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folio");

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Product", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.ProductCategory", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Products")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.ProductCategory", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("ProductCategories")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Reservations")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Unit", "Unit")
                        .WithMany("Reservations")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Glamping");

                    b.Navigation("Guest");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Stay", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Stays")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Stays")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AllegroService.Domain.Entities.Unit", "Unit")
                        .WithMany("Stays")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");

                    b.Navigation("Reservation");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.StockBalance", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("StockBalances")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Location", "Location")
                        .WithMany("StockBalances")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Product", "Product")
                        .WithMany("StockBalances")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("StockMovements")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Location", "Location")
                        .WithMany("StockMovements")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AllegroService.Domain.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Unit", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Units")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.User", b =>
                {
                    b.HasOne("AllegroService.Domain.Entities.Glamping", "Glamping")
                        .WithMany("Users")
                        .HasForeignKey("GlampingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Glamping");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Charge", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Folio", b =>
                {
                    b.Navigation("Charges");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Glamping", b =>
                {
                    b.Navigation("ChargeItems");

                    b.Navigation("Charges");

                    b.Navigation("Folios");

                    b.Navigation("Guests");

                    b.Navigation("Locations");

                    b.Navigation("Payments");

                    b.Navigation("ProductCategories");

                    b.Navigation("Products");

                    b.Navigation("Reservations");

                    b.Navigation("Stays");

                    b.Navigation("StockBalances");

                    b.Navigation("StockMovements");

                    b.Navigation("Units");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Guest", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Location", b =>
                {
                    b.Navigation("StockBalances");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Product", b =>
                {
                    b.Navigation("ChargeItems");

                    b.Navigation("StockBalances");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Stays");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Stay", b =>
                {
                    b.Navigation("Folios");
                });

            modelBuilder.Entity("AllegroService.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Reservations");

                    b.Navigation("Stays");
                });
#pragma warning restore 612, 618
        }
    }
}
